[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "simple_boot",
]

[dependencies]
bootloader = "0.10.8"
font8x8 = { version = "0.2.7", default-features = false, features = ["unicode"], optional = true }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.4.9"

[features]
default = ["font8x8"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"