#[target.'cfg(target_os = "none")']
[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
runner = "cargo run --target x86_64-pc-windows-msvc --package boot --"

[target.'cfg(all(target_arch = "aarch64"), target_os = "darwin")']
runner = "cargo run --target aarch64-apple-darwin --package boot --"

[alias]
kbuild = "build --target x86_64-rust_os.json"
kimage = "run --target x86_64-rust_os.json -- --no-run"
krun = "run --target x86_64-rust_os.json"
ktest = "test --target x86_64-rust_os.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]